import { prisma } from '@/lib/prisma'
import { newDrugsData } from '../scripts/seedNewDrugs'

/**
 * Seeds the standard Ayurvedic drug catalog for a newly registered hospital.
 * Each hospital gets their own independent copy they can customize.
 */
export async function seedHospitalCatalog(hospitalId: number) {
  const baseDrugs = [
    { name: 'Abhayarishta', category: 'Arishta', size_amount: 750, size_unit: 'ml', unit_price: 1810 },
    { name: 'Amurtharishta', category: 'Arishta', size_amount: 750, size_unit: 'ml', unit_price: 1180 },
    { name: 'Arjunarishta', category: 'Arishta', size_amount: 750, size_unit: 'ml', unit_price: 1690 },
    { name: 'Ashokarishta', category: 'Arishta', size_amount: 750, size_unit: 'ml', unit_price: 1020 },
    { name: 'Ashwagandarishta', category: 'Arishta', size_amount: 750, size_unit: 'ml', unit_price: 2750 },
    { name: 'Balarishta', category: 'Arishta', size_amount: 750, size_unit: 'ml', unit_price: 1950 },
    { name: 'Danthyarishta', category: 'Arishta', size_amount: 750, size_unit: 'ml', unit_price: 820 },
    { name: 'Dashamoolarishta', category: 'Arishta', size_amount: 750, size_unit: 'ml', unit_price: 1780 },
    { name: 'Draksharishta', category: 'Arishta', size_amount: 750, size_unit: 'ml', unit_price: 2570 },
    { name: 'Kadirarishta', category: 'Arishta', size_amount: 750, size_unit: 'ml', unit_price: 2720 },
    { name: 'Musthakadyarishta', category: 'Arishta', size_amount: 750, size_unit: 'ml', unit_price: 1030 },
    { name: 'Nimbarishta', category: 'Arishta', size_amount: 750, size_unit: 'ml', unit_price: 780 },
    { name: 'Saraswatharishta', category: 'Arishta', size_amount: 750, size_unit: 'ml', unit_price: 770 },
    { name: 'Chirabilwadi Kwathaya', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 2030 },
    { name: 'Danthimoola Kawatha', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 1100 },
    { name: 'Danyapanchaka Kawatha', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 1180 },
    { name: 'Daruparpata Kawatha', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 1260 },
    { name: 'Dashamoola Kawatha', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 910 },
    { name: 'Deniba Debatu Kawatha', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 1090 },
    { name: 'Dewadara Panchaka', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 1270 },
    { name: 'Eranda Sapthaka', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 920 },
    { name: 'Madhu Meha Harani', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 1210 },
    { name: 'Madhu Meha Harani', category: 'Kwatha', size_amount: 500, size_unit: 'ml', unit_price: 700 },
    { name: 'Medha Harani Kawatha', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 1370 },
    { name: 'Nawakarshaka Kwatha', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 1930 },
    { name: 'Panchamoola Kawatha', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 1960 },
    { name: 'Patola Katukahiru', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 2190 },
    { name: 'Prathyaksha Dathree', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 970 },
    { name: 'Punarnawashtaka', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 2220 },
    { name: 'Rashna Sapthaka', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 1160 },
    { name: 'Sreshta Nimba', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 1010 },
    { name: 'Thrikatukadi', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 2150 },
    { name: 'Thripala Kwatha', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 1050 },
    { name: 'Thrikaluhingu', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 5410 },
    { name: 'Yakshakshyadi', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 1280 },
    { name: 'Maha Rashnadi', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 1700 },
    { name: 'Shariwadi', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 2300 },
    { name: 'Rashna Seegru', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 1150 },
    { name: 'Hardradi Kwatha', category: 'Kwatha', size_amount: 750, size_unit: 'ml', unit_price: 1160 },
    { name: 'Arawindasawaya', category: 'Asawa', size_amount: 750, size_unit: 'ml', unit_price: 880 },
    { name: 'Chandanasawaya', category: 'Asawa', size_amount: 750, size_unit: 'ml', unit_price: 900 },
    { name: 'Kanakasawaya', category: 'Asawa', size_amount: 750, size_unit: 'ml', unit_price: 980 },
    { name: 'Louhasawaya', category: 'Asawa', size_amount: 750, size_unit: 'ml', unit_price: 1060 },
    { name: 'Pipplyadasawaya', category: 'Asawa', size_amount: 750, size_unit: 'ml', unit_price: 1030 },
    { name: 'Punarnawasawaya', category: 'Asawa', size_amount: 750, size_unit: 'ml', unit_price: 890 },
    { name: 'Sharibadyasawaya', category: 'Asawa', size_amount: 750, size_unit: 'ml', unit_price: 1660 },
    { name: 'Ushirasawaya', category: 'Asawa', size_amount: 750, size_unit: 'ml', unit_price: 890 },
    { name: 'Chawanaprasawa Leha', category: 'Leha', size_amount: 400, size_unit: 'g', unit_price: 2530 },
    { name: 'Kantakaryawa Leha', category: 'Leha', size_amount: 400, size_unit: 'g', unit_price: 3950 },
    { name: 'Kushmandakawa Leha', category: 'Leha', size_amount: 400, size_unit: 'g', unit_price: 4480 },
    { name: 'Wasawa Leha', category: 'Leha', size_amount: 400, size_unit: 'g', unit_price: 1500 },
    { name: 'Wellawengayam Leha', category: 'Leha', size_amount: 400, size_unit: 'g', unit_price: 2150 },
    { name: 'Suwadarani', category: 'Covid Items', size_amount: 500, size_unit: 'g', unit_price: 870 },
    { name: 'Suwadarani', category: 'Covid Items', size_amount: 100, size_unit: 'g', unit_price: 300 },
    { name: 'Guduchchadi Kasaya', category: 'Covid Items', size_amount: 500, size_unit: 'g', unit_price: 2960 },
    { name: 'Guduchchadi Kasaya', category: 'Covid Items', size_amount: 100, size_unit: 'g', unit_price: 790 },
    { name: 'Doomayanaya', category: 'Covid Items', size_amount: 100, size_unit: 'g', unit_price: 240 },
    { name: 'Sandalwood Face Wash', category: 'Face Wash', size_amount: 100, size_unit: 'ml', unit_price: 460 },
    { name: 'Sandalwood Face Wash', category: 'Face Wash', size_amount: 50, size_unit: 'ml', unit_price: 290 },
    { name: 'Papaya Face Wash', category: 'Face Wash', size_amount: 100, size_unit: 'ml', unit_price: 490 },
    { name: 'Papaya Face Wash', category: 'Face Wash', size_amount: 50, size_unit: 'ml', unit_price: 280 },
    { name: 'Cucumber Face Wash', category: 'Face Wash', size_amount: 100, size_unit: 'ml', unit_price: 450 },
    { name: 'Cucumber Face Wash', category: 'Face Wash', size_amount: 50, size_unit: 'ml', unit_price: 280 },
    { name: 'Carot Face Wash', category: 'Face Wash', size_amount: 100, size_unit: 'ml', unit_price: 280 },
    { name: 'Carot Face Wash', category: 'Face Wash', size_amount: 50, size_unit: 'ml', unit_price: 160 },
    { name: 'Raktha Chandan Face Wash', category: 'Face Wash', size_amount: 100, size_unit: 'ml', unit_price: 480 },
    { name: 'Raktha Chandan Face Wash', category: 'Face Wash', size_amount: 50, size_unit: 'ml', unit_price: 320 },
    { name: 'Jeewalepa Balm', category: 'Balm', size_amount: 115, size_unit: 'g', unit_price: 270 },
    { name: 'Jeewalepa Balm', category: 'Balm', size_amount: 210, size_unit: 'g', unit_price: 195 },
    { name: 'Jeewalepa Balm', category: 'Balm', size_amount: 305, size_unit: 'g', unit_price: 80 },
    { name: 'Ranahansa (Gajabala)', category: 'Rasayana', size_amount: 50, size_unit: 'g', unit_price: 2750 },
    { name: 'Weniwel Hand Wash', category: 'Hand Wash', size_amount: 300, size_unit: 'ml', unit_price: 890 },
    { name: 'Iramusu (Tea Bags)', category: 'Tea Bags', size_amount: 1, size_unit: 'Qty', unit_price: 800 },
    { name: 'Cinnamon (Tea Bags)', category: 'Tea Bags', size_amount: 1, size_unit: 'Qty', unit_price: 600 },
    { name: 'Kothalahimbutu (Tea Bags)', category: 'Tea Bags', size_amount: 1, size_unit: 'Qty', unit_price: 350 },
    { name: 'Masbedda (Mix)', category: 'Tea Bags', size_amount: 1, size_unit: 'Qty', unit_price: 520 },
    { name: 'Masbedda (Mix)', category: 'Tea Bags', size_amount: 1, size_unit: 'Qty', unit_price: 280 },
    { name: 'Nelli Rasakinda', category: 'Tea Bags', size_amount: 1, size_unit: 'Qty', unit_price: 440 },
    { name: 'Paspanguwa', category: 'General', size_amount: 50, size_unit: 'g', unit_price: 140 },
    { name: 'Peyawa', category: 'General', size_amount: 5, size_unit: 'g', unit_price: 40 },
    { name: 'Thambumhodi (Rasam)', category: 'General', size_amount: 5, size_unit: 'g', unit_price: 35 },
    { name: 'Sudu Hadun Powder', category: 'General', size_amount: 50, size_unit: 'g', unit_price: 475 },
    { name: 'Citronella Oil', category: 'General', size_amount: 50, size_unit: 'ml', unit_price: 380 },
    { name: 'Weniwel Sanitizer', category: 'General', size_amount: 100, size_unit: 'ml', unit_price: 480 },
    { name: 'Bulath Sape', category: 'General', size_amount: 30, size_unit: 'g', unit_price: 160 },
    { name: 'Ashwaganda Cap', category: 'Capsules', size_amount: 250, size_unit: 'g', unit_price: 4740 },
    { name: 'Sudarshana Cap', category: 'Capsules', size_amount: 250, size_unit: 'g', unit_price: 5910 },
    { name: 'Mruththyunjaya', category: 'Rasa', size_amount: 250, size_unit: 'g', unit_price: 24000 },
    { name: 'Punarnawadi Mandura', category: 'Rasa', size_amount: 250, size_unit: 'g', unit_price: 13000 },
    { name: 'Ramabana Rasa', category: 'Rasa', size_amount: 250, size_unit: 'g', unit_price: 10200 },
    { name: 'Somanatha Rasa', category: 'Rasa', size_amount: 250, size_unit: 'g', unit_price: 6060 },
    { name: 'Makaradwajaya', category: 'Rasa', size_amount: 250, size_unit: 'g', unit_price: 185560 },
    { name: 'Swasakutara Rasa', category: 'Rasa', size_amount: 250, size_unit: 'g', unit_price: 15050 },
    { name: 'Tribuwana Keerthi Rasa', category: 'Rasa', size_amount: 250, size_unit: 'g', unit_price: 15550 },
    { name: 'Wathagajendra Rasa', category: 'Rasa', size_amount: 250, size_unit: 'g', unit_price: 12680 },
    { name: 'Kameshwaree Modaka', category: 'Modaka', size_amount: 50, size_unit: 'g', unit_price: 430 },
    { name: 'Madana Modaka', category: 'Modaka', size_amount: 100, size_unit: 'g', unit_price: 750 },
    { name: 'Bee Honey', category: 'Oils & Honey', size_amount: 250, size_unit: 'ml', unit_price: 1500 },
    { name: 'Castor Oil', category: 'Oils & Honey', size_amount: 250, size_unit: 'ml', unit_price: 1040 },
    { name: 'Ghee', category: 'Oils & Honey', size_amount: 250, size_unit: 'ml', unit_price: 1900 },
    { name: 'Mee Oil', category: 'Oils & Honey', size_amount: 250, size_unit: 'ml', unit_price: 990 },
    { name: 'Khomba Oil', category: 'Oils & Honey', size_amount: 250, size_unit: 'ml', unit_price: 1150 },
    { name: 'Mustard Oil', category: 'Oils & Honey', size_amount: 250, size_unit: 'ml', unit_price: 920 },
    { name: 'Sesame Oil', category: 'Oils & Honey', size_amount: 250, size_unit: 'ml', unit_price: 750 },
    { name: 'Mouth Wash (1/10 Pack)', category: 'Mouth Wash', size_amount: 1, size_unit: 'Pack', unit_price: 160 },
    { name: 'Mouth Wash (25 Pack)', category: 'Mouth Wash', size_amount: 1, size_unit: 'Pack', unit_price: 340 },
    { name: 'Komarika Shampoo', category: 'Shampoo', size_amount: 105, size_unit: 'ml', unit_price: 430 },
    { name: 'Dharani', category: 'Syrup', size_amount: 750, size_unit: 'ml', unit_price: 2260 },
    { name: 'Dharani', category: 'Syrup', size_amount: 200, size_unit: 'ml', unit_price: 650 },
    { name: 'Kantakaree', category: 'Syrup', size_amount: 750, size_unit: 'ml', unit_price: 4520 },
    { name: 'Maduka', category: 'Syrup', size_amount: 750, size_unit: 'ml', unit_price: 2590 },
    { name: 'Siddha Jeewa Mrutha', category: 'Syrup', size_amount: 750, size_unit: 'ml', unit_price: 6400 },
    { name: 'Siddha Jeewa Mrutha', category: 'Syrup', size_amount: 500, size_unit: 'ml', unit_price: 4280 },
    { name: 'Wasaka Sirap', category: 'Syrup', size_amount: 750, size_unit: 'ml', unit_price: 1200 },
    { name: 'Weniwel Body Wash', category: 'Body Wash', size_amount: 300, size_unit: 'ml', unit_price: 940 },
    { name: 'Weniwel Body Wash', category: 'Body Wash', size_amount: 210, size_unit: 'ml', unit_price: 590 },
    { name: 'Weniwel Body Wash', category: 'Body Wash', size_amount: 100, size_unit: 'ml', unit_price: 350 },
    { name: 'Pancha Walkala BW', category: 'Body Wash', size_amount: 300, size_unit: 'ml', unit_price: 830 },
    { name: 'Pancha Walkala BW', category: 'Body Wash', size_amount: 210, size_unit: 'ml', unit_price: 560 },
    { name: 'Pancha Walkala BW', category: 'Body Wash', size_amount: 100, size_unit: 'ml', unit_price: 275 },
    { name: 'Buddharaja Kalka', category: 'Kalka', size_amount: 250, size_unit: 'g', unit_price: 7515 },
    { name: 'Chandra Kalka', category: 'Kalka', size_amount: 250, size_unit: 'g', unit_price: 1550 },
    { name: 'Desadun Kalka', category: 'Kalka', size_amount: 400, size_unit: 'g', unit_price: 1840 },
    { name: 'Desadun Kalka', category: 'Kalka', size_amount: 250, size_unit: 'g', unit_price: 1180 },
    { name: 'Nawarathna Kalka', category: 'Kalka', size_amount: 250, size_unit: 'g', unit_price: 1000 },
    { name: 'Sharkaradi Kalka', category: 'Kalka', size_amount: 250, size_unit: 'g', unit_price: 2050 },
    { name: 'Lakshadi', category: 'Lepa', size_amount: 250, size_unit: 'g', unit_price: 1180 },
    { name: 'Roganikash', category: 'Lepa', size_amount: 250, size_unit: 'g', unit_price: 1380 },
    { name: 'Thiladilepa', category: 'Lepa', size_amount: 250, size_unit: 'g', unit_price: 1400 },
    { name: 'Awipaththikara', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 2600 },
    { name: 'Ashwaganda', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 1460 },
    { name: 'Bhushkaralawana', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 2050 },
    { name: 'Dashanga Lepa', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 3050 },
    { name: 'Dathree Choorna', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 810 },
    { name: 'Hinguwashtaka', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 7970 },
    { name: 'Hisathel Game Choorna', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 5930 },
    { name: 'Jathipaladi', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 1980 },
    { name: 'Katpala Choorna', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 990 },
    { name: 'Manibadra', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 1200 },
    { name: 'Pushyanuga', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 4280 },
    { name: 'Seethopaladi', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 3170 },
    { name: 'Shrungayadi', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 4990 },
    { name: 'Sudarshana', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 2710 },
    { name: 'Sukumara', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 730 },
    { name: 'Thalisadi', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 1970 },
    { name: 'Thripala', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 1020 },
    { name: 'Wajjakshara', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 3570 },
    { name: 'Safufe Surinjan', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 2200 },
    { name: 'Shoolaharani', category: 'Choorna', size_amount: 500, size_unit: 'g', unit_price: 1250 },
    { name: 'Ashwaganda', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 6000 },
    { name: 'Ashwaganda', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 4700 },
    { name: 'Bakuchi', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 2450 },
    { name: 'Bakuchi', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 2035 },
    { name: 'Batu', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 5720 },
    { name: 'Batu', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 5260 },
    { name: 'Brungamalaka', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 6000 },
    { name: 'Brungamalaka', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 5370 },
    { name: 'Diwyanganadi', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 3170 },
    { name: 'Diwyanganadi', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 2732 },
    { name: 'Irimedadi', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 3780 },
    { name: 'Irimedadi', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 3245 },
    { name: 'Kedumbidum', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 3000 },
    { name: 'Kedumbidum', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 2472 },
    { name: 'Kolashleshma', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 5500 },
    { name: 'Kolashleshma', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 5035 },
    { name: 'Maha Koranda', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 6400 },
    { name: 'Maha Koranda', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 5915 },
    { name: 'Maha Masha', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 8250 },
    { name: 'Maha Masha', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 7710 },
    { name: 'Narayana', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 5950 },
    { name: 'Narayana', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 5100 },
    { name: 'Neelyadi', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 3710 },
    { name: 'Neelyadi', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 3080 },
    { name: 'Nilma', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 1750 },
    { name: 'Nirgundiyadi', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 3650 },
    { name: 'Nirgundiyadi', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 3350 },
    { name: 'Pata', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 6300 },
    { name: 'Pata', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 5145 },
    { name: 'Pranajeewa', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 7090 },
    { name: 'Peenus', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 4380 },
    { name: 'Peenus', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 3745 },
    { name: 'Pinda', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 3950 },
    { name: 'Pinda', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 3165 },
    { name: 'Sarshapadi', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 3450 },
    { name: 'Sarshapadi', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 2800 },
    { name: 'Sarwavishadi', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 6240 },
    { name: 'Sarwavishadi', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 5390 },
    { name: 'Seethodaka', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 4500 },
    { name: 'Seethodaka', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 3730 },
    { name: 'Shoolahara', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 3550 },
    { name: 'Shoolahara', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 3010 },
    { name: 'Siddhartha', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 5500 },
    { name: 'Siddhartha', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 5325 },
    { name: 'Thripala', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 3600 },
    { name: 'Thripala', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 3000 },
    { name: 'Visarpahara', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 3560 },
    { name: 'Wathawiduranga', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 8050 },
    { name: 'Wathawiduranga', category: 'Thailaya', size_amount: 700, size_unit: 'ml', unit_price: 7225 },
    { name: 'Kenda Peralum Thailaya', category: 'Thailaya', size_amount: 750, size_unit: 'ml', unit_price: 3272 },
    { name: 'Chandrapraba Wati', category: 'Vati', size_amount: 250, size_unit: 'g', unit_price: 3950 },
    { name: 'Krimigathani Wati', category: 'Vati', size_amount: 250, size_unit: 'g', unit_price: 3225 },
    { name: 'Jeewananda Wati', category: 'Vati', size_amount: 250, size_unit: 'g', unit_price: 10900 },
    { name: 'Maha Sanka Wati', category: 'Vati', size_amount: 250, size_unit: 'g', unit_price: 11300 },
    { name: 'Maha Sanka Wati', category: 'Vati', size_amount: 50, size_unit: 'g', unit_price: 2310 },
    { name: 'Sarpaganda Wati', category: 'Vati', size_amount: 250, size_unit: 'g', unit_price: 1330 },
    { name: 'Arogyawardhana Wati', category: 'Vati', size_amount: 250, size_unit: 'g', unit_price: 9000 },
    { name: 'Seetharama Wati', category: 'Vati', size_amount: 250, size_unit: 'g', unit_price: 5300 },
    { name: 'Suranvidura Wati', category: 'Vati', size_amount: 250, size_unit: 'g', unit_price: 7960 },
    { name: 'Gokshuradi Gugul', category: 'Gugul', size_amount: 250, size_unit: 'g', unit_price: 4480 },
    { name: 'Kaishor Gugul', category: 'Gugul', size_amount: 250, size_unit: 'g', unit_price: 4110 },
    { name: 'Yogaraja Gugul', category: 'Gugul', size_amount: 250, size_unit: 'g', unit_price: 3470 },
    { name: 'Kanchanara Gugul', category: 'Gugul', size_amount: 250, size_unit: 'g', unit_price: 3030 },
    { name: 'Kanchanara Gugul', category: 'Gugul', size_amount: 100, size_unit: 'g', unit_price: 1250 },
    { name: 'Daripala Pethi', category: 'Tablets', size_amount: 250, size_unit: 'g', unit_price: 1000 },
    { name: 'Medhaharani Pethi', category: 'Tablets', size_amount: 250, size_unit: 'g', unit_price: 1500 },
    { name: 'Daruparpata Pethi', category: 'Tablets', size_amount: 250, size_unit: 'g', unit_price: 2620 },
    { name: 'Daruparpata Pethi', category: 'Tablets', size_amount: 200, size_unit: 'g', unit_price: 2120 },
    { name: 'Sudarshana Pethi', category: 'Tablets', size_amount: 250, size_unit: 'g', unit_price: 3250 },
    { name: 'Sudarshana Pethi', category: 'Tablets', size_amount: 200, size_unit: 'g', unit_price: 2650 },
    { name: 'Aralu Pethi', category: 'Tablets', size_amount: 250, size_unit: 'g', unit_price: 798 },
    { name: 'Panchamoola Lagu Pethi', category: 'Tablets', size_amount: 250, size_unit: 'g', unit_price: 5647 },
    { name: 'Panchamoola Lagu Pethi', category: 'Tablets', size_amount: 200, size_unit: 'g', unit_price: 4525 },
    { name: 'Denibadiya Kasaya Pethi', category: 'Tablets', size_amount: 200, size_unit: 'g', unit_price: 2570 },
    { name: 'Panthimoola Bala Shun', category: 'Tablets', size_amount: 200, size_unit: 'g', unit_price: 2970 },
    { name: 'Rashna Sapthaka Pethi', category: 'Tablets', size_amount: 200, size_unit: 'g', unit_price: 2630 },
    { name: 'Eranda Sapthaka Pethi', category: 'Tablets', size_amount: 200, size_unit: 'g', unit_price: 1780 },
    { name: 'Etho Komarika Hand Jel', category: 'Hand Jel', size_amount: 300, size_unit: 'ml', unit_price: 900 },
    { name: 'Etho Komarika Hand Jel', category: 'Hand Jel', size_amount: 65, size_unit: 'ml', unit_price: 235 },
    { name: 'Etho Komarika Hand Jel', category: 'Hand Jel', size_amount: 50, size_unit: 'ml', unit_price: 190 },
    { name: 'Wili Pottani', category: 'New Products', size_amount: 1, size_unit: 'Box', unit_price: 500 },
    { name: 'First Aid Box', category: 'New Products', size_amount: 1, size_unit: 'Box', unit_price: 6600 },
    { name: 'Essential Oil Pack', category: 'New Products', size_amount: 1, size_unit: 'Box', unit_price: 1425 },
    { name: 'Kaishor Gugul', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 462 },
    { name: 'Gokshura Gugul', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 520 },
    { name: 'Yogaraja Gugul', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 445 },
    { name: 'Meda Harani Pethi', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 368 },
    { name: 'Thripala Pethi', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 329 },
    { name: 'Sudarshana Pethi', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 414 },
    { name: 'Daruparpata Pethi', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 613 },
    { name: 'Sudarshana Capsule', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 553 },
    { name: 'Suwadarani Capsule', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 530 },
    { name: 'Cinnamon Capsule', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 507 },
    { name: 'Kothalahimbutu Capsule', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 492 },
    { name: 'Dathri Capsule', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 537 },
    { name: 'Medaharani Capsule', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 491 },
    { name: 'Ashwaganda Capsule', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 549 },
    { name: 'Tribuwan Keerthi Rasa', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 531 },
    { name: 'Punarnawadi Mandura', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 1143 },
    { name: 'Mruthyunjaya Rasa', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 714 },
    { name: 'Ramabana Rasa', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 445 },
    { name: 'Wathagajendrasinha', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 447 },
    { name: 'Swasa Kutara Rasa', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 620 },
    { name: 'Somanatha Rasa', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 327 },
    { name: 'Arogya Wardana Vati', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 394 },
    { name: 'Krimi Gathani Vati', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 344 },
    { name: 'Seetharama Vati', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 341 },
    { name: 'Jeewananda Vati', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 440 },
    { name: 'Suran Vidura Vati', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 384 },
    { name: 'Maha Sanka Vati', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 1329 },
    { name: 'Sarpagandha Vati', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 316 },
    { name: 'Chandraprabha Vati', category: 'Blister Pack', size_amount: 30, size_unit: 's', unit_price: 516 },
  ]

  const defaultDrugs = [...baseDrugs, ...newDrugsData]

  const getDoseForCategory = (cat: string): number => {
    switch (cat) {
      case 'Arishta':
      case 'Asawa':
      case 'Kwatha':
      case 'Syrup':
      case 'Body Wash':
      case 'Face Wash':
      case 'Shampoo':
      case 'Hand Wash':
      case 'Hand Jel':
      case 'Mouth Wash':
        return 120
      case 'Leha':
      case 'Kalka':
      case 'Choorna':
      case 'Rasayana':
        return 20
      case 'Lepa':
      case 'Balm':
        return 30
      case 'Oils & Honey':
      case 'Thailaya':
        return 60
      case 'Bhasma':
      case 'Senthuram':
      case 'Rasa':
        return 16
      default:
        return 8
    }
  }

  // Batch insert all drugs for the new hospital
  await prisma.drug.createMany({
    data: defaultDrugs.map((drug) => ({
      ...drug,
      hospital_id: hospitalId,
      standard_dose: getDoseForCategory(drug.category),
    })),
  })
}
